import ply.lex as lex
# List of token names.   This is always required
tokens = (
   'equipos',
   'nombre_equipo',
   'identidad_equipo',
   'link',
   'asignatura',
   'carrera',
   'universidad_regional',
   'direccion',
   'calle',
   'ciudad',
   'pais',
   'alianza_equipo',
   'integrantes',
   'nombre',
   'edad',
   'cargo',
   'foto',
   'email',
   'habilidades',
   'salario',
   'activo',
   'proyectos',
   'estado',
   'resumen',
   'fecha_inicio',
   'fecha_fin',
   'video',
   'conclusion',
   'version',
   'firma digital',
   'l_llaves',
   'r_llaves',
   'l_corchetes',
   'r_corchete',
)
